version: '3.5'
##############
services:
  proxy-nginx:
    image: jwilder/nginx-proxy
    container_name: proxy-nginx
    env_file: env/proxy-nginx.env
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - proxy-network
    volumes: 
      - "proxy-certs:/etc/nginx/certs"
      - "proxy-dhparam:/etc/nginx/dhparam"
      - "proxy-vhost:/etc/nginx/vhost.d"
      - "proxy-html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock"
  
  proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy-companion
    env_file: env/proxy-companion.env
    networks: 
      - proxy-network
    volumes:
      - "proxy-html:/usr/share/nginx/html"
      - "proxy-certs:/etc/nginx/certs"
      - "proxy-vhost:/etc/nginx/vhost.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  portainer:
    image: portainer/portainer
    container_name: portainer
    env_file: env/portainer.env
    networks: 
      - proxy-network
    volumes:
      - "portainer-data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=${HOST_PORTAINER}
      - LETSENCRYPT_HOST=${HOST_PORTAINER}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    env_file: env/gitlab.env
    networks:
      - proxy-network
    volumes:
      - "git-config:/etc/gitlab"
      - "git-logs:/var/log/gitlab"
      - "git-data:/var/opt/gitlab"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=${HOST_GITLAB}
      - LETSENCRYPT_HOST=${HOST_GITLAB}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    env_file: env/nextcloud.env
    networks:
      - proxy-network
    volumes:
      - "cloud-web:/var/www/html"
      - "cloud-config:/var/www/html/config"
      - "cloud-apps:/var/www/html/custom_apps"
      - "cloud-data:/var/www/html/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=${HOST_NEXTCLOUD}
      - LETSENCRYPT_HOST=${HOST_NEXTCLOUD}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

  teamspeak:
      image: polinux/teamspeak
      container_name: teamspeak
      env_file: env/teamspeak.env
      entrypoint: /bootstrap.sh
      ports:
        - 9987:9987/udp
        - 10011:10011
        - 30033:30033
      volumes:
        - "teamspeak-data:/opt/teamspeak"

  
##############
volumes:
  proxy-html:
     name: "proxy-html"
  proxy-certs:
     name: "proxy-certs"
  proxy-vhost:
     name: "proxy-vhost"
  proxy-dhparam:
     name: "proxy-dhparam"
  portainer-data:
    name: "portainer-data"
  git-config:
    name: "git-config"
  git-logs: 
    name: "git-logs"
  git-data:
    name: "git-data"
  cloud-web:
    name: cloud-web
  cloud-config:
    name: cloud-config
  cloud-apps:
    name: cloud-apps
  cloud-data:
    name: cloud-data
  teamspeak-data:
    name: teamspeak-data
  wekan-data:
    name: wekan-data
  mail-data:
    name: mail-data
  mail-state:
    name: mail-state
  
##############
networks:
  proxy-network:
    name: proxy-network
  db-network:
    name: db-network
    driver: bridge